version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-app:latest
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 Hello.wsgi:application"
    volumes:
      - .:/app  # Mount current project directory into the container
      - ./db:/app/db  # Persist the SQLite database
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=Hello.settings
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
