name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get remove -y containerd  # Remove conflicting containerd package
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose

    - name: Build Docker image
      run: docker-compose build

    - name: Save Docker image
      run: docker save -o django_app.tar web

    - name: Deploy to EC2
      env:
        EC2_IP: ${{ secrets.EC2_IP }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts

        # Copy Docker image to EC2
        scp -o StrictHostKeyChecking=no django_app.tar ubuntu@$EC2_IP:/home/ubuntu/

        # Load Docker image and deploy
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "docker load -i /home/ubuntu/django_app.tar"
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "docker-compose down"
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "docker-compose up -d"
