name: Deploy Django Application

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t my_django_app .

      - name: SSH to EC2 and deploy
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem  # Saving the private key to a file
          chmod 600 private_key.pem  # Securing the key file
          
          # SSH into EC2 and execute deployment commands
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # Stop and remove the existing Docker container (if any)
            docker stop my_django_container || true
            docker rm my_django_container || true

            # Pull the latest Docker image (if you are using Docker Hub or ECR)
            # Uncomment the line below if you're pulling from Docker Hub/ECR
            # docker pull your_dockerhub_username/my_django_app

            # Run the new Docker container with the latest image
            docker run -d --name my_django_container -p 8000:8000 my_django_app
          EOF
