name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}  # Ensure this secret contains your EC2's IP
          username: ubuntu  # Ensure 'ubuntu' is used since your EC2 uses Ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}  # Ensure the correct private key is stored in secrets
          script: |
            # Check if the /app directory exists; if not, create it
            if [ ! -d "/app" ]; then
              echo "Directory /app not found. Cloning repository..."
              git clone https://github.com/your-repository-url.git /app
            else
              cd /app
              git pull origin main
            fi
            
            # Install docker-compose if not already installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Build, down, and up the Docker containers
            docker-compose -f /app/docker-compose.yml build
            docker-compose -f /app/docker-compose.yml down
            docker-compose -f /app/docker-compose.yml up -d
