name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Runs on push to 'main' branch

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your GitHub Actions self-hosted runner
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOYMENT_EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy code to EC2
        run: |
          rsync -avz --exclude='db/*' \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
            ./ ubuntu@${{ secrets.DEPLOYMENT_EC2_IP }}:/home/ubuntu/django-app

      - name: Start Django with Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.DEPLOYMENT_EC2_IP }} << 'EOF'
            cd /home/ubuntu/django-app
            docker-compose down
            docker-compose up --build -d
            docker system prune -af
          EOF
