name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t django-app:latest .
          docker save django-app:latest | gzip > django-app.tar.gz

      - name: Transfer Docker Image to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          scp -o StrictHostKeyChecking=no -i "$SSH_KEY" django-app.tar.gz ubuntu@${{ secrets.EC2_HOST }}:~/django-app.tar.gz

      - name: SSH to EC2 and Deploy
        env:
          SSH_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i "$SSH_KEY" ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            gunzip -c ~/django-app.tar.gz | docker load
            docker stop django_app || true
            docker rm django_app || true
            docker run -d \
              --name django_app \
              -p 8000:8000 \
              django-app:latest
EOF
