name: Django Deployment to EC2

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch

jobs:
  deploy:
    name: Build and Deploy Django App to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH for Deployment
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22

    - name: Copy Project Files to EC2
      run: |
        rsync -avz --exclude='.git' --exclude='.github' . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/django-app/

    - name: Install Dependencies and Run Docker Compose on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/${{ secrets.EC2_USER }}/django-app
          docker-compose down || true
          docker-compose build
          docker-compose up -d
        EOF
