name: CI/CD Pipeline for AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      APP_NAME: my_app_name

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js (Optional)
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install Dependencies
      run: |
        npm install  # Change this command based on your project

    - name: Test Application (Optional)
      run: npm run test

    - name: Archive App for Deployment
      run: zip -r app.zip .

    - name: Transfer Files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "app.zip"
        target: "~/"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo apt update
          unzip -o app.zip -d /var/www/html/
          sudo systemctl restart nginx
