name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Django SECRET_KEY
      run: echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV

    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          # Export the Django SECRET_KEY
          export DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}"
          # Perform your Django deployment steps here
          cd /path/to/your/django/project
          source venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --noinput
          # Restart the application server if necessary (e.g., Gunicorn, Nginx)
          sudo systemctl restart gunicorn
        EOF
